openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Receive list of products
      description: Receive list of all available products.
      responses:
        "200":
          description: Success
