service: aws-mentorship
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-esbuild
  - serverless-dynamodb-local

custom:
  webpackIncludeModules: true

functions:
  getProductsById:
    handler: functions/getProductsById.getProductsById
    module:
    name: product
    events:
      - http:
          path: /products/{id}
          method: get

  getProductsList:
    handler: functions/getProductsList.getProductsList
    name: products
    events:
      - http:
          path: /products
          method: get

  createProduct:
    handler: functions/createProduct.createProduct
    name: createProduct
    events:
      - http:
          path: /products
          method: post

resources:
  Resources:
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    stockModel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stockModel
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
